version: "3.8"

services:
    lavalink:
        image: ghcr.io/azarath7/lavalink-jre22:latest
        container_name: lavalink
        restart: unless-stopped
        environment:
            - _JAVA_OPTIONS=-Xmx1G
            - SERVER_ADDRESS=0.0.0.0
            - SERVER_PORT=2333
            - LAVALINK_SERVER_PASSWORD=password
        volumes:
            ## Use "./" if you want to create a mount from your current directory (where docker-compose.yml is located)
            ## Having access to files INSIDE the container is complicated. Mount function is used to have access to certain container files or folders.
            ## Read more: https://docs.docker.com/storage/bind-mounts/ 
            - ./application.yml:/opt/Lavalink/application.yml
        networks:
            - vocardbot
        expose:
            - "2333"

    # # You can selfhost MongoDB. Just uncomment lines starting with single "#" below.
    # mongo:
    #     image: mongo:latest
    #     container_name: mongo
    #     restart: unless-stopped
    #     volumes:
    #         # Use "./" if you want to create a mount from your current directory (where docker-compose.yml is located)
    #         # Having access to files INSIDE the container is complicated. Mount function is used to have access to certain container files or folders.
    #         # Read more: https://docs.docker.com/storage/bind-mounts/ 
    #         - ./data/mongo/db:/data/db
    #         - ./data/mongo/conf:/data/configdb
    #     environment:
    #         - MONGO_INITDB_ROOT_USERNAME=admin
    #         - MONGO_INITDB_ROOT_PASSWORD=admin
    #     expose:
    #         - "27017"
    #     networks:
    #         - local
    #     command: ["mongod", "--oplogSize=1024", "--wiredTigerCacheSizeGB=1", "--auth", "--noscripting"]

    vocard:
        image: ghcr.io/azarath7/vocard-dashboard:latest
        container_name: vocard
        volumes:
            - ./settings.json:/app/settings.json
            - ./logs/supervisor/:/var/log
        environment:
            - TOKEN=XXXXXXXXXXXXXXXXXXXXXXXX.XXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXX
            - CLIENT_ID=123456789012345678
            - CLIENT_SECRET_ID=XXXXXXXXXX-XXXXXXXXXXXXXXXXXXXXX
            - SERCET_KEY=DASHBOARD_SERCET_KEY
            - BUG_REPORT_CHANNEL_ID=123456789012345678
            - SPOTIFY_CLIENT_ID=0XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            - SPOTIFY_CLIENT_SECRET=0XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            - GENIUS_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            - MONGODB_URL=mongodb+srv://user:password@clusterURL
            - MONGODB_NAME=YOUR_MONGODB_NAME
            - REDIRECT_URI=http://YOUR_PUBLIC_IP:37123

        depends_on:
            lavalink:
                condition: service_started
            # mongo:
            #     condition: service_started
        networks:
            - vocardbot
        #ports:
            #- 37123:37123

networks:
    vocardbot:
        name: vocardbot
