version: "3.8"

services:
    lavalink:
    ## If having issues with latest lavalink package try this one instead:
    ## ghcr.io/lavalink-devs/lavalink@sha256:1ad5dcdef90b6c98aaac948874de0a2d286914847fcc0a1b4a8c593f47cdbb45
        image: ghcr.io/lavalink-devs/lavalink:latest
        container_name: lavalink
        restart: unless-stopped
        environment:
    #        More environment variables here: https://lavalink.dev/configuration/index.html#example-environment-variables
            - _JAVA_OPTIONS=-Xmx1G
            - SERVER_PORT=2333
        volumes:
      - ./application.yml:/opt/Lavalink/application.yml
        networks:
            - vocardbot
        expose:
            - "2333"

    # # You can selfhost MongoDB. Just uncomment lines starting with single "#" below.
    # mongo:
    #     image: mongo:latest
    #     container_name: mongo
    #     restart: unless-stopped
    #     volumes:
    #         # Use "./" if you want to create a mount from your current directory (where docker-compose.yml is located)
    #         # Having access to files INSIDE the container is complicated. Mount function is used to have access to certain container files or folders.
    #         # Read more: https://docs.docker.com/storage/bind-mounts/ 
    #         - ./data/mongo/db:/data/db
    #         - ./data/mongo/conf:/data/configdb
    #     environment:
    #         - MONGO_INITDB_ROOT_USERNAME=admin
    #         - MONGO_INITDB_ROOT_PASSWORD=admin
    #     expose:
    #         - "27017"
    #     networks:
    #         - local
    #     command: ["mongod", "--oplogSize=1024", "--wiredTigerCacheSizeGB=1", "--auth", "--noscripting"]

    vocard:
    ## Choco, you should add :latest tag istead of :v2.6.8 to your current build, so you won't have to rewrite docker-compose.yml after each update
        image: ghcr.io/chocomeow/vocard:v2.6.8
        container_name: vocard
        volumes:
            ## Use "./" if you want to create a mount from your current directory (where docker-compose.yml is located)
            ## Having access to files INSIDE the container is complicated. Mount function is used to have access to certain container files or folders.
            ## Read more: https://docs.docker.com/storage/bind-mounts/ 
            - ./settings.json:/app/settings.json
        environment:
            - TOKEN=XXXXXXXXXXXXXXXXXXXXXXXX.XXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXX
            - CLIENT_ID=123456789012345678
            - CLIENT_SECRET_ID=XXXXXXXXXX-XXXXXXXXXXXXXXXXXXXXX
            - SERCET_KEY=DASHBOARD_SERCET_KEY
            - BUG_REPORT_CHANNEL_ID=123456789012345678
            - SPOTIFY_CLIENT_ID=0XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            - SPOTIFY_CLIENT_SECRET=0XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            - GENIUS_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            - MONGODB_URL=mongodb+srv://user:password@clusterURL
            - MONGODB_NAME=Vocard

        depends_on:
            lavalink:
                condition: service_started
            # mongo:
            #     condition: service_started
        networks:
            - vocardbot
        #expose:
            #- "37123"

networks:
    vocardbot:
        name: vocardbot
